# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FizzyMd < Formula
  desc "Transparent Markdown→HTML wrapper for Fizzy CLI"
  homepage "https://github.com/zainfathoni/fizzy-md"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zainfathoni/fizzy-md/releases/download/v0.1.5/fizzy-md_0.1.5_Darwin_x86_64.tar.gz"
      sha256 "7c8fef4ffb2eb80e45f1886e4f7518e2ba166afce68d8b2c3794ca440b49eba7"

      def install
        bin.install "fizzy-md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zainfathoni/fizzy-md/releases/download/v0.1.5/fizzy-md_0.1.5_Darwin_arm64.tar.gz"
      sha256 "c7091ef9c7bf475356e8697a3339b6501c8b159abbd18cab2df0a7d3a8ae36c6"

      def install
        bin.install "fizzy-md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zainfathoni/fizzy-md/releases/download/v0.1.5/fizzy-md_0.1.5_Linux_x86_64.tar.gz"
      sha256 "50cef6e64aebbe5b4df3e92bd46c71d8e0292f19bdbfc2fe803bd5da7ad952f4"
      def install
        bin.install "fizzy-md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zainfathoni/fizzy-md/releases/download/v0.1.5/fizzy-md_0.1.5_Linux_arm64.tar.gz"
      sha256 "913d22cf29e418e7b98606e9c677082ec7f7bafdc5509de79cebe9891ee76f0f"
      def install
        bin.install "fizzy-md"
      end
    end
  end

  test do
    system "#{bin}/fizzy-md --version"
  end
end
